// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tsoy.emrmock.domain;

import com.tsoy.emrmock.domain.AD_RolesDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AD_RolesDataOnDemand_Roo_Configurable {
    
    declare @type: AD_RolesDataOnDemand: @Configurable;
    
}
