// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tsoy.emrmock.domain;

import com.tsoy.emrmock.domain.AD_Roles;
import com.tsoy.emrmock.domain.AD_RolesDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AD_RolesDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AD_RolesDataOnDemand: @Component;
    
    private Random AD_RolesDataOnDemand.rnd = new SecureRandom();
    
    private List<AD_Roles> AD_RolesDataOnDemand.data;
    
    public AD_Roles AD_RolesDataOnDemand.getNewTransientAD_Roles(int index) {
        AD_Roles obj = new AD_Roles();
        setRole_id(obj, index);
        setRole_name(obj, index);
        return obj;
    }
    
    public void AD_RolesDataOnDemand.setRole_id(AD_Roles obj, int index) {
        Long role_id = new Integer(index).longValue();
        obj.setRole_id(role_id);
    }
    
    public void AD_RolesDataOnDemand.setRole_name(AD_Roles obj, int index) {
        String role_name = "role_name_" + index;
        obj.setRole_name(role_name);
    }
    
    public AD_Roles AD_RolesDataOnDemand.getSpecificAD_Roles(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AD_Roles obj = data.get(index);
        Long id = obj.getId();
        return AD_Roles.findAD_Roles(id);
    }
    
    public AD_Roles AD_RolesDataOnDemand.getRandomAD_Roles() {
        init();
        AD_Roles obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return AD_Roles.findAD_Roles(id);
    }
    
    public boolean AD_RolesDataOnDemand.modifyAD_Roles(AD_Roles obj) {
        return false;
    }
    
    public void AD_RolesDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = AD_Roles.findAD_RolesEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AD_Roles' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AD_Roles>();
        for (int i = 0; i < 10; i++) {
            AD_Roles obj = getNewTransientAD_Roles(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
