// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tsoy.emrmock.domain;

import com.tsoy.emrmock.domain.AD_RolesDataOnDemand;
import com.tsoy.emrmock.domain.AD_RolesIntegrationTest;
import com.tsoy.emrmock.domain.users.AD_Roles;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AD_RolesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AD_RolesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AD_RolesIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AD_RolesIntegrationTest: @Transactional;
    
    @Autowired
    AD_RolesDataOnDemand AD_RolesIntegrationTest.dod;
    
    @Test
    public void AD_RolesIntegrationTest.testCountAD_Roleses() {
        Assert.assertNotNull("Data on demand for 'AD_Roles' failed to initialize correctly", dod.getRandomAD_Roles());
        long count = AD_Roles.countAD_Roleses();
        Assert.assertTrue("Counter for 'AD_Roles' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AD_RolesIntegrationTest.testFindAD_Roles() {
        AD_Roles obj = dod.getRandomAD_Roles();
        Assert.assertNotNull("Data on demand for 'AD_Roles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AD_Roles' failed to provide an identifier", id);
        obj = AD_Roles.findAD_Roles(id);
        Assert.assertNotNull("Find method for 'AD_Roles' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AD_Roles' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AD_RolesIntegrationTest.testFindAllAD_Roleses() {
        Assert.assertNotNull("Data on demand for 'AD_Roles' failed to initialize correctly", dod.getRandomAD_Roles());
        long count = AD_Roles.countAD_Roleses();
        Assert.assertTrue("Too expensive to perform a find all test for 'AD_Roles', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AD_Roles> result = AD_Roles.findAllAD_Roleses();
        Assert.assertNotNull("Find all method for 'AD_Roles' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AD_Roles' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AD_RolesIntegrationTest.testFindAD_RolesEntries() {
        Assert.assertNotNull("Data on demand for 'AD_Roles' failed to initialize correctly", dod.getRandomAD_Roles());
        long count = AD_Roles.countAD_Roleses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AD_Roles> result = AD_Roles.findAD_RolesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AD_Roles' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AD_Roles' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AD_RolesIntegrationTest.testFlush() {
        AD_Roles obj = dod.getRandomAD_Roles();
        Assert.assertNotNull("Data on demand for 'AD_Roles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AD_Roles' failed to provide an identifier", id);
        obj = AD_Roles.findAD_Roles(id);
        Assert.assertNotNull("Find method for 'AD_Roles' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAD_Roles(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AD_Roles' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AD_RolesIntegrationTest.testMergeUpdate() {
        AD_Roles obj = dod.getRandomAD_Roles();
        Assert.assertNotNull("Data on demand for 'AD_Roles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AD_Roles' failed to provide an identifier", id);
        obj = AD_Roles.findAD_Roles(id);
        boolean modified =  dod.modifyAD_Roles(obj);
        Integer currentVersion = obj.getVersion();
        AD_Roles merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AD_Roles' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AD_RolesIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AD_Roles' failed to initialize correctly", dod.getRandomAD_Roles());
        AD_Roles obj = dod.getNewTransientAD_Roles(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AD_Roles' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AD_Roles' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'AD_Roles' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AD_RolesIntegrationTest.testRemove() {
        AD_Roles obj = dod.getRandomAD_Roles();
        Assert.assertNotNull("Data on demand for 'AD_Roles' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AD_Roles' failed to provide an identifier", id);
        obj = AD_Roles.findAD_Roles(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AD_Roles' with identifier '" + id + "'", AD_Roles.findAD_Roles(id));
    }
    
}
