// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tsoy.emrmock.domain;

import com.tsoy.emrmock.domain.Assessment;
import com.tsoy.emrmock.domain.AssessmentDataOnDemand;
import com.tsoy.emrmock.domain.AssessmentIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AssessmentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AssessmentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AssessmentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AssessmentIntegrationTest: @Transactional;
    
    @Autowired
    AssessmentDataOnDemand AssessmentIntegrationTest.dod;
    
    @Test
    public void AssessmentIntegrationTest.testCountAssessments() {
        Assert.assertNotNull("Data on demand for 'Assessment' failed to initialize correctly", dod.getRandomAssessment());
        long count = Assessment.countAssessments();
        Assert.assertTrue("Counter for 'Assessment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AssessmentIntegrationTest.testFindAssessment() {
        Assessment obj = dod.getRandomAssessment();
        Assert.assertNotNull("Data on demand for 'Assessment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Assessment' failed to provide an identifier", id);
        obj = Assessment.findAssessment(id);
        Assert.assertNotNull("Find method for 'Assessment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Assessment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AssessmentIntegrationTest.testFindAllAssessments() {
        Assert.assertNotNull("Data on demand for 'Assessment' failed to initialize correctly", dod.getRandomAssessment());
        long count = Assessment.countAssessments();
        Assert.assertTrue("Too expensive to perform a find all test for 'Assessment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Assessment> result = Assessment.findAllAssessments();
        Assert.assertNotNull("Find all method for 'Assessment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Assessment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AssessmentIntegrationTest.testFindAssessmentEntries() {
        Assert.assertNotNull("Data on demand for 'Assessment' failed to initialize correctly", dod.getRandomAssessment());
        long count = Assessment.countAssessments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Assessment> result = Assessment.findAssessmentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Assessment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Assessment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AssessmentIntegrationTest.testFlush() {
        Assessment obj = dod.getRandomAssessment();
        Assert.assertNotNull("Data on demand for 'Assessment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Assessment' failed to provide an identifier", id);
        obj = Assessment.findAssessment(id);
        Assert.assertNotNull("Find method for 'Assessment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAssessment(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Assessment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AssessmentIntegrationTest.testMergeUpdate() {
        Assessment obj = dod.getRandomAssessment();
        Assert.assertNotNull("Data on demand for 'Assessment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Assessment' failed to provide an identifier", id);
        obj = Assessment.findAssessment(id);
        boolean modified =  dod.modifyAssessment(obj);
        Integer currentVersion = obj.getVersion();
        Assessment merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Assessment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AssessmentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Assessment' failed to initialize correctly", dod.getRandomAssessment());
        Assessment obj = dod.getNewTransientAssessment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Assessment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Assessment' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Assessment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AssessmentIntegrationTest.testRemove() {
        Assessment obj = dod.getRandomAssessment();
        Assert.assertNotNull("Data on demand for 'Assessment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Assessment' failed to provide an identifier", id);
        obj = Assessment.findAssessment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Assessment' with identifier '" + id + "'", Assessment.findAssessment(id));
    }
    
}
