// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tsoy.emrmock.domain;

import com.tsoy.emrmock.domain.CNA_Record;
import com.tsoy.emrmock.domain.CNA_RecordDataOnDemand;
import com.tsoy.emrmock.domain.CNA_RecordIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CNA_RecordIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CNA_RecordIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CNA_RecordIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CNA_RecordIntegrationTest: @Transactional;
    
    @Autowired
    CNA_RecordDataOnDemand CNA_RecordIntegrationTest.dod;
    
    @Test
    public void CNA_RecordIntegrationTest.testCountCNA_Records() {
        Assert.assertNotNull("Data on demand for 'CNA_Record' failed to initialize correctly", dod.getRandomCNA_Record());
        long count = CNA_Record.countCNA_Records();
        Assert.assertTrue("Counter for 'CNA_Record' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CNA_RecordIntegrationTest.testFindCNA_Record() {
        CNA_Record obj = dod.getRandomCNA_Record();
        Assert.assertNotNull("Data on demand for 'CNA_Record' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CNA_Record' failed to provide an identifier", id);
        obj = CNA_Record.findCNA_Record(id);
        Assert.assertNotNull("Find method for 'CNA_Record' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CNA_Record' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CNA_RecordIntegrationTest.testFindAllCNA_Records() {
        Assert.assertNotNull("Data on demand for 'CNA_Record' failed to initialize correctly", dod.getRandomCNA_Record());
        long count = CNA_Record.countCNA_Records();
        Assert.assertTrue("Too expensive to perform a find all test for 'CNA_Record', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CNA_Record> result = CNA_Record.findAllCNA_Records();
        Assert.assertNotNull("Find all method for 'CNA_Record' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CNA_Record' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CNA_RecordIntegrationTest.testFindCNA_RecordEntries() {
        Assert.assertNotNull("Data on demand for 'CNA_Record' failed to initialize correctly", dod.getRandomCNA_Record());
        long count = CNA_Record.countCNA_Records();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CNA_Record> result = CNA_Record.findCNA_RecordEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CNA_Record' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CNA_Record' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CNA_RecordIntegrationTest.testFlush() {
        CNA_Record obj = dod.getRandomCNA_Record();
        Assert.assertNotNull("Data on demand for 'CNA_Record' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CNA_Record' failed to provide an identifier", id);
        obj = CNA_Record.findCNA_Record(id);
        Assert.assertNotNull("Find method for 'CNA_Record' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCNA_Record(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CNA_Record' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CNA_RecordIntegrationTest.testMergeUpdate() {
        CNA_Record obj = dod.getRandomCNA_Record();
        Assert.assertNotNull("Data on demand for 'CNA_Record' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CNA_Record' failed to provide an identifier", id);
        obj = CNA_Record.findCNA_Record(id);
        boolean modified =  dod.modifyCNA_Record(obj);
        Integer currentVersion = obj.getVersion();
        CNA_Record merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CNA_Record' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CNA_RecordIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CNA_Record' failed to initialize correctly", dod.getRandomCNA_Record());
        CNA_Record obj = dod.getNewTransientCNA_Record(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CNA_Record' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CNA_Record' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'CNA_Record' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CNA_RecordIntegrationTest.testRemove() {
        CNA_Record obj = dod.getRandomCNA_Record();
        Assert.assertNotNull("Data on demand for 'CNA_Record' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CNA_Record' failed to provide an identifier", id);
        obj = CNA_Record.findCNA_Record(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'CNA_Record' with identifier '" + id + "'", CNA_Record.findCNA_Record(id));
    }
    
}
