// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tsoy.emrmock.domain;

import com.tsoy.emrmock.domain.CNA_RecordIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CNA_RecordIntegrationTest_Roo_Configurable {
    
    declare @type: CNA_RecordIntegrationTest: @Configurable;
    
}
