// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tsoy.emrmock.domain.patients;

import com.tsoy.emrmock.domain.patients.PatientInfo;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PatientInfo_Roo_Configurable {
    
    declare @type: PatientInfo: @Configurable;
    
}
