// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tsoy.emrmock.domain.users;

import com.tsoy.emrmock.domain.users.AD_Roles;

privileged aspect AD_Roles_Roo_JavaBean {
    
    public String AD_Roles.getRole_name() {
        return this.role_name;
    }
    
    public void AD_Roles.setRole_name(String role_name) {
        this.role_name = role_name;
    }
    
}
